### ISSUE TITLE
Formatting/stle checklist

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#27]
To review for before finalizing:

- [ ] Apply Black
- [ ] Thousands separator `x = 1_000_000` instead of `x = 1000000`.
- [ ] Data as plural rather than singular
- [ ] f-strings for formatting output `print(f'Sum of squares = {sum_of_squares_vectorized:0.4f}')`
- [ ] Avoid print() statements for single, unformatted outputs
