### ISSUE TITLE
Punch list

### ISSUE THREAD

**Issue by kylebradbury** [nickeubank/mids_coursera#72]
Course Checks:
- [x] Complete joint review of Course 2 content and exercises for final edits / coherence
- [x] Contribute to Course 1 intro script (ETA 11/2)
- [x] Create intro video script #77 (ETA 11/4)
- [x] Film into video
- [x] #75 (ETA 11/4)
- [x] Review for formatting consistency (i.e. run Black on everything)
- [x] Change Image Config to use jupyter console
- [x] JWST exercise (or similar)
- [x] Make matrix vectorization example a lab
- [ ] Add short conceptual quizzes (with 4-5 questions)

Kyle-specific Components and Timeline
- [X] Merge in c3w2and4 branch into main @kylebradbury (ETA: 10/24)
- [x] Complete incorporating remaining changes @kylebradbury (ETA: 10/24)
- [x] Close the merge issue for c3w2and4 @kylebradbury (ETA 10/24)
- [x] Clean up the majority of outstanding issues @kylebradbury
- [x] Finalize Course 2 exercise content for publishing @kylebradbury (ETA 10/31)
- [x] Color reading finalization @kylebradbury #79 
- [x] Film last live coding video
- [x] Array headers / references issue #63 

Changes to propagate to Coursera:
- [ ] [Axes added/modified to matrices figures](https://github.com/nickeubank/mids_coursera/commit/ebeb953ce8bca4d4017d4d3d67f97e02546dadab)
- [ ] [Error in figure corrected and need to update the figure in Coursera](https://github.com/nickeubank/mids_coursera/commit/336d622aa2c1f3747ae191ee27f2477a69c5b560)
- [ ] [Add modifying subsets figures and text from corresponding commit](https://github.com/nickeubank/mids_coursera/commit/9b153d01718451be29d1a9b59fbad6ceba09ee3f)
- [ ] Add reading on variables as pointers [from this commit](https://github.com/nickeubank/mids_coursera/commit/905b6e9d0fbfa54535b6bc302fabacad33e37f40) and [this commit](https://github.com/nickeubank/mids_coursera/commit/f7494b34232c68016e296a558ac139bbb1ac9966)
- [ ] [Reordered and expanded the color images reading](https://github.com/nickeubank/mids_coursera/commit/609217d33a296aa349bf201f5afc0fe0a5d34757)
- [ ] [Ran Grammarly on everything](https://github.com/nickeubank/mids_coursera/commit/10430ed30ae9f2f30db10914de4325123241f9c1) 
- [ ] For each exercise in Week 4, have the exercise, then the solution so students can check their work

Nick-specific Components and Timeline
- [x] Finalize graded matrix exercise #58 (ETA: by 11/2)
- [x] Jupyter Console Intro (ETA 11/11) 

Michael-specific Components
- [x] Add in two missing readings # 68 and #69 @mvhudson-duke

Drew & Genevieve Review
- [ ] Review the [reading that touches on memory](https://github.com/nickeubank/mids_coursera/blob/main/class_2/week_3/13_objects_and_variables.ipynb) for consistency with Course 1

**Comment by nickeubank** [comment]
I think that all looks great! As we finalize / make changes to images, we also have to make sure that we propagate those to all the right places (e.g., change files here AND update coursera images)

**Comment by mvhudson-duke** [comment]
@kylebradbury @nickeubank, the Michael-Specific components are finished and in coursera!

**Comment by mvhudson-duke** [comment]
@nickeubank @kylebradbury I think all the coursera changes have been propagated, except for the Week 4 solutions. Once everyone is back from the holiday, we can figure out exactly what we want to do there. Thanks!

**Comment by kylebradbury** [comment]
Looks like we're good-to-go on Course 2, so I'll close this issue now (reopen if anything comes up)
